<a href="https://colab.research.google.com/github/AbhinavShakunt/MY_Data_Science_Notebooks/blob/main/word_embadding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [9]:
one_hot("amazing restaurant",30)

[24, 8]

In [10]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[1, 5], [24, 8], [10, 2], [6, 22, 5], [2, 25, 18], [1, 5], [27, 25, 25], [14, 24], [14, 1], [27, 14]]


In [11]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 1  5  0  0]
 [24  8  0  0]
 [10  2  0  0]
 [ 6 22  5  0]
 [ 2 25 18  0]
 [ 1  5  0  0]
 [27 25 25  0]
 [14 24  0  0]
 [14  1  0  0]
 [27 14  0  0]]


In [12]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [13]:
X = padded_reviews
y = sentiment

In [14]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten_1 (Flatten)         (None, 20)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 21        
                                                                 
Total params: 171 (684.00 Byte)
Trainable params: 171 (684.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [21]:
model.fit(X, y, epochs=100, verbose=0)

In [22]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 30ms/step - loss: 0.1386 - accuracy: 0.9000


0.8999999761581421

In [25]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [26]:
weights[13]

array([-0.04673409, -0.00094119,  0.04274625,  0.00320851, -0.0417912 ],
      dtype=float32)

In [27]:
weights[4]

array([ 0.00680839, -0.02203504,  0.01920388, -0.00453073, -0.03636143],
      dtype=float32)

In [28]:
weights[16]

array([-0.01757159,  0.02643862, -0.00217005, -0.03848754, -0.04180403],
      dtype=float32)